# Changes here will be overwritten by Copier
_commit: a37bdf5
_src_path: https://github.com/Elements-Experimental/euclide
default_branch: dev
metrics_enabled: true
metrics_sheet_name: review_dashboard
project_name: euclide-testbed
tech_stack: Markdown
